### ISSUE TITLE
rotateDeg

### ISSUE THREAD

**Issue by pmousse** [maxkueng/victor#20]
Not sure what is wrong, but if I do the following :

var v = new Victor(0,1);
var y = v.clone().rotateDeg(180);
console.log(y);

I was expecting x:0 y:-1, instead I get 
x: -1.2246467991473532e-16
y: -1

**Comment by maxkueng** [comment]
This is most likely related to #15. I haven't gotten around it yet.

**Comment by pmousse** [comment]
I have applied the following workaround :
var y = v.clone().rotateDeg(180)
console.log(y.x.toFixed(15));
You loose a tiny bit in precision, but anyway dividing by PI is not precise ;)
Thank you.

**Comment by maxkueng** [comment]
I don't think JavaScript can achieve better precision in divisions. You should be able to use the result for any further calculations and it shouldn't make a difference. 

I've added a `.toFixed([precision=8])` method in version 1.1.0. So you can do

``` js
var v1 = new Victor(0, 1);
var v2 = v1.clone()
           .rotate(Math.PI)
           .toFixed(15);
```
