### ISSUE TITLE
Missing clamp method

### ISSUE THREAD

**Issue by vanrez-nez** [maxkueng/victor#38]
The current implementation of `limit` assumes that a multiplier should affect both components of the vector. Other libraries would just clamp the values to a given min, max range. Have you thought about adding a `clamp` method?

Cheers

**Comment by phivk** [comment]
similarly to a `clamp` method, I'd like something like a `cutOff` or `limitMagnitude`, which limit the vector's magnitude to a specified maximum magnitude.

p5.js's [`limit()` method](https://github.com/processing/p5.js/blob/4c2f42b67aebdb89ca307e37840b329bd3413f46/src/math/p5.Vector.js#L559-L584) works like this.

**Comment by dundass** [comment]
it would be great if the API was changed so that no 2nd arg to `limit()` clamped it to the magnitude of the 1st arg. but this project seems to be abandoned so not holding out much hope
